import type { Species } from '../../types'
import type { Grant, GrantQuery, GrantSource, Practice } from './types'

// Seeded grant catalog for the demo. Program names and agencies are real; award
// amounts, cost-share rates, deadlines and eligibility are simplified, illustrative
// values, not current program terms. Replace with a live GrantSource before real use.

const ALL: Species[] = ['Hog', 'Cattle', 'Grain']
const LIVESTOCK: Species[] = ['Hog', 'Cattle']

// Conservation practices reused across programs (NRCS practice standard codes where they exist).
const P = {
  windbreak: { code: '380', name: 'Windbreak and shelterbelt around barns (odor and visual screen)', topics: ['siting-odor'], operations: LIVESTOCK, unit: 'site', unitCost: 8500 },
  covers: { code: '367', name: 'Roofs and covers on manure storage', topics: ['siting-odor', 'manure'], operations: LIVESTOCK, unit: 'site', unitCost: 60000 },
  storage: { code: '313', name: 'Waste storage facility upgrade', topics: ['manure', 'nutrients'], operations: LIVESTOCK, unit: 'site', unitCost: 140000 },
  nmp: { code: '590', name: 'Nutrient management plan', topics: ['nutrients', 'water-quality'], operations: ALL, unit: 'operation', unitCost: 4500 },
  cover: { code: '340', name: 'Cover crop', topics: ['nutrients', 'water-quality', 'conservation'], operations: ['Grain', 'Cattle'], unit: '100 acres', unitCost: 5500 },
  hua: { code: '561', name: 'Heavy use area protection at feeding and loading areas', topics: ['manure', 'water-quality'], operations: ['Cattle'], unit: 'site', unitCost: 32000 },
  grazing: { code: '528', name: 'Prescribed grazing', topics: ['conservation', 'water-quality'], operations: ['Cattle'], unit: '100 acres', unitCost: 1800 },
  filter: { code: '393', name: 'Filter strip below livestock areas', topics: ['manure', 'water-quality'], operations: LIVESTOCK, unit: 'site', unitCost: 6500 },
  waterway: { code: '412', name: 'Grassed waterway', topics: ['conservation', 'water-quality'], operations: ['Grain'], unit: '100 acres', unitCost: 3000 },
  inhibitor: { name: 'Nitrification inhibitor with fall nitrogen', topics: ['nutrients', 'water-quality'], operations: ['Grain'], unit: '100 acres', unitCost: 900 },
} satisfies Record<string, Practice>

const DISTRICT = (who: string) => `The county Soil and Water Conservation District office (${who})`
const STATE_FORMS = ['Program application from the local conservation district', 'Farm map with practice locations', 'Contractor quotes for each practice']

type CatalogEntry = Omit<Grant, 'kind' | 'funds'> & Partial<Pick<Grant, 'kind' | 'funds'>>

const ENTRIES: CatalogEntry[] = [
  // ---------- federal ----------
  {
    id: 'nrcs-eqip',
    name: 'Environmental Quality Incentives Program',
    shortName: 'NRCS EQIP',
    agency: 'USDA Natural Resources Conservation Service',
    level: 'Federal',
    summary: 'Cost-share for conservation practices on working farms: manure storage and covers, odor screening, nutrient management, cover crops and grazing.',
    topics: ['siting-odor', 'manure', 'nutrients', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Farm and tract records established with the Farm Service Agency' },
      { kind: 'confirm', label: 'Average adjusted gross income under $900,000 (form CCC-941)' },
      { kind: 'confirm', label: 'Conservation compliance on highly erodible land and wetlands (form AD-1026)' },
      { kind: 'confirm', label: 'Control of the land for the length of the contract' },
    ],
    award: { max: 450000, costSharePct: 75, basis: 'Typically 50 to 75% of practice cost (up to 90% for historically underserved producers), up to a $450,000 payment limit per producer' },
    deadline: { kind: 'annual', month: 11, day: 14, label: 'State ranking cutoff (applications are taken year-round and batched)' },
    practices: [P.windbreak, P.covers, P.storage, P.nmp, P.cover, P.hua, P.grazing],
    attachments: ['NRCS-CPA-1200 Conservation Program Application', 'AD-1026 Highly Erodible Land and Wetland Conservation Certification', 'CCC-941 Average Adjusted Gross Income Certification', 'CCC-902 Farm Operating Plan', 'AD-2047 Customer Data Worksheet'],
    applyVia: 'The local USDA Service Center (NRCS field office) for the county',
    sourceUrl: 'https://www.nrcs.usda.gov/',
  },
  {
    id: 'nrcs-csp',
    name: 'Conservation Stewardship Program',
    shortName: 'NRCS CSP',
    agency: 'USDA Natural Resources Conservation Service',
    level: 'Federal',
    summary: 'Five-year payments for operations that already meet conservation standards and add enhancements, such as precision nutrient management.',
    topics: ['nutrients', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Already meets the stewardship threshold for at least two resource concerns' },
      { kind: 'confirm', label: 'Farm and tract records established with the Farm Service Agency' },
      { kind: 'confirm', label: 'Average adjusted gross income under $900,000 (form CCC-941)' },
    ],
    award: { max: 200000, costSharePct: 100, basis: 'Annual payments over a five-year contract (minimum $4,000 a year), up to $200,000 per producer' },
    deadline: { kind: 'annual', month: 2, day: 13, label: 'Ranking cutoff for the next sign-up' },
    practices: [
      { code: 'E590', name: 'Enhancement: precision nutrient management', topics: ['nutrients', 'water-quality'], operations: ALL, unit: '100 acres', unitCost: 2500 },
      { code: 'E340', name: 'Enhancement: multi-species cover crop', topics: ['conservation', 'water-quality'], operations: ['Grain', 'Cattle'], unit: '100 acres', unitCost: 3500 },
    ],
    attachments: ['NRCS-CPA-1200 Conservation Program Application', 'CCC-941 Average Adjusted Gross Income Certification', 'AD-1026 Highly Erodible Land and Wetland Conservation Certification', 'Conservation stewardship assessment worksheet'],
    applyVia: 'The local USDA Service Center (NRCS field office) for the county',
    sourceUrl: 'https://www.nrcs.usda.gov/',
  },
  {
    id: 'aphis-adt',
    name: 'Animal Disease Traceability: official EID tags',
    shortName: 'APHIS EID tags',
    agency: 'USDA APHIS Veterinary Services, with the state animal health official',
    level: 'Federal',
    summary: 'Official RFID ear tags for cattle at no cost while program supplies last, to meet electronic ID rules for interstate movement.',
    topics: ['traceability'],
    operations: ['Cattle'],
    eligibility: [
      { kind: 'operation', operations: ['Cattle'] },
      { kind: 'confirm', label: 'Premises identification number (PIN) registered with the state' },
    ],
    award: { max: 15000, costSharePct: 100, basis: 'Tags are supplied free while supplies last; readers and software are not covered' },
    deadline: { kind: 'rolling', label: 'While tag supplies last' },
    practices: [{ name: 'Official 840-series RFID ear tags', topics: ['traceability'], operations: ['Cattle'], unit: '1k head', unitCost: 2800 }],
    attachments: ['Premises identification registration', 'Tag order form from the state veterinarian’s office'],
    applyVia: 'The state animal health official (state veterinarian’s office)',
    sourceUrl: 'https://www.aphis.usda.gov/',
  },

  // ---------- state ----------
  {
    id: 'il-cpp',
    name: 'Conservation Practices Program (Partners for Conservation)',
    shortName: 'Illinois CPP',
    agency: 'Illinois Department of Agriculture',
    level: 'State',
    state: 'IL',
    summary: 'State cost-share through county conservation districts for practices that protect water quality, including runoff control below livestock areas.',
    topics: ['manure', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['IL'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Practice approved by the county district before construction starts' },
    ],
    award: { max: 10000, costSharePct: 60, basis: 'Up to 60% of practice cost, up to $10,000 per applicant per year' },
    deadline: { kind: 'annual', month: 12, day: 15, label: 'County district sign-up deadline' },
    practices: [P.filter, P.waterway, P.cover],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Illinois'),
  },
  {
    id: 'il-fcss',
    name: 'Fall Covers for Spring Savings',
    shortName: 'Illinois cover crop discount',
    agency: 'Illinois Department of Agriculture',
    level: 'State',
    state: 'IL',
    summary: 'A crop insurance premium discount for acres planted to cover crops.',
    topics: ['nutrients', 'water-quality'],
    operations: ['Grain'],
    eligibility: [
      { kind: 'state', states: ['IL'] },
      { kind: 'operation', operations: ['Grain'] },
      { kind: 'confirm', label: 'Federal crop insurance on the enrolled acres' },
      { kind: 'confirm', label: 'Acres not enrolled in another cover crop cost-share' },
    ],
    award: { max: 2500, costSharePct: 100, basis: '$5 per acre off next year’s premium, up to 500 acres' },
    deadline: { kind: 'annual', month: 1, day: 15, label: 'Enrollment deadline' },
    practices: [{ code: '340', name: 'Cover crop premium discount ($5 per acre)', topics: ['nutrients', 'water-quality'], operations: ['Grain'], unit: '100 acres', unitCost: 500 }],
    attachments: ['Enrollment form', 'Crop insurance policy number', 'Field list with cover crop acres'],
    applyVia: 'The Illinois Department of Agriculture enrollment portal',
  },
  {
    id: 'ia-wqi',
    name: 'Water Quality Initiative cost share',
    shortName: 'Iowa WQI',
    agency: 'Iowa Department of Agriculture and Land Stewardship',
    level: 'State',
    state: 'IA',
    summary: 'Per-acre cost share for first-time cover crops, nitrogen practices and edge-of-field practices under the Iowa Nutrient Reduction Strategy.',
    topics: ['nutrients', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['IA'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Practice not already used on these acres' },
    ],
    award: { max: 10000, costSharePct: 50, basis: 'About 50% of practice cost, up to $10,000 per operation' },
    deadline: { kind: 'rolling', label: 'Rolling, first come through the county district' },
    practices: [P.cover, P.inhibitor, P.nmp],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Iowa'),
  },
  {
    id: 'ia-ifip',
    name: 'Iowa Financial Incentives Program',
    shortName: 'Iowa IFIP',
    agency: 'Iowa Department of Agriculture and Land Stewardship',
    level: 'State',
    state: 'IA',
    summary: 'Cost share for permanent soil and water practices, including runoff control at livestock sites.',
    topics: ['conservation', 'manure', 'water-quality'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['IA'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Practice maintained for its design life (usually 10 to 20 years)' },
    ],
    award: { max: 15000, costSharePct: 50, basis: 'Up to 50% of practice cost, up to $15,000 per operation' },
    deadline: { kind: 'rolling', label: 'Rolling, funds allocated by county district' },
    practices: [P.filter, P.waterway, P.hua],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Iowa'),
  },
  {
    id: 'in-cwi',
    name: 'Clean Water Indiana',
    shortName: 'Clean Water Indiana',
    agency: 'Indiana State Department of Agriculture',
    level: 'State',
    state: 'IN',
    summary: 'County district cost share for nutrient, manure and soil health practices.',
    topics: ['nutrients', 'manure', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['IN'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Located in a county with an active Clean Water Indiana grant' },
    ],
    award: { max: 10000, costSharePct: 50, basis: 'Up to 50% of practice cost, up to $10,000 per applicant' },
    deadline: { kind: 'annual', month: 11, day: 1, label: 'County district application deadline' },
    practices: [P.nmp, P.filter, P.cover],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Indiana'),
  },
  {
    id: 'mn-agri-lig',
    name: 'AGRI Livestock Investment Grant',
    shortName: 'Minnesota AGRI Livestock',
    agency: 'Minnesota Department of Agriculture',
    level: 'State',
    state: 'MN',
    summary: 'Grants toward livestock facility improvements, including manure storage, odor control and housing upgrades.',
    topics: ['manure', 'siting-odor', 'animal-housing'],
    operations: LIVESTOCK,
    eligibility: [
      { kind: 'state', states: ['MN'] },
      { kind: 'operation', operations: LIVESTOCK },
      { kind: 'confirm', label: 'Minnesota resident who is the principal operator' },
    ],
    award: { max: 50000, costSharePct: 10, basis: '10% of the project cost, up to $50,000' },
    deadline: { kind: 'annual', month: 2, day: 5, label: 'Annual application deadline' },
    practices: [P.storage, P.covers, P.windbreak],
    attachments: ['Grant application', 'Project budget and quotes', 'Proof of Minnesota residency'],
    applyVia: 'The Minnesota Department of Agriculture grants portal',
  },
  {
    id: 'nc-acsp',
    name: 'Agriculture Cost Share Program',
    shortName: 'North Carolina ACSP',
    agency: 'North Carolina Division of Soil and Water Conservation',
    level: 'State',
    state: 'NC',
    summary: 'Cost share for animal waste management and water quality practices, delivered through county districts.',
    topics: ['manure', 'nutrients', 'water-quality', 'siting-odor'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['NC'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Existing operation (the program does not fund new facilities)' },
    ],
    award: { max: 75000, costSharePct: 75, basis: 'Up to 75% of practice cost, up to $75,000 per year' },
    deadline: { kind: 'annual', month: 12, day: 31, label: 'District ranking deadline' },
    practices: [P.covers, P.storage, P.filter],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('North Carolina'),
  },
  {
    id: 'ne-nswcp',
    name: 'Nebraska Soil and Water Conservation Program',
    shortName: 'Nebraska NSWCP',
    agency: 'Nebraska Department of Natural Resources, through the local Natural Resources District',
    level: 'State',
    state: 'NE',
    summary: 'Cost share for soil and water practices, including livestock runoff control.',
    topics: ['conservation', 'water-quality', 'manure'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['NE'] }, { kind: 'operation', operations: ALL }],
    award: { max: 15000, costSharePct: 50, basis: 'Up to 50% of practice cost' },
    deadline: { kind: 'rolling', label: 'Rolling, through the Natural Resources District' },
    practices: [P.filter, P.hua, P.waterway],
    attachments: STATE_FORMS,
    applyVia: 'The local Natural Resources District office',
  },
  {
    id: 'oh-h2ohio',
    name: 'H2Ohio nutrient management incentives',
    shortName: 'H2Ohio',
    agency: 'Ohio Department of Agriculture',
    level: 'State',
    state: 'OH',
    summary: 'Per-acre incentives for voluntary nutrient management plans, manure incorporation and cover crops.',
    topics: ['nutrients', 'manure', 'water-quality'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['OH'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Fields in an eligible H2Ohio watershed' },
    ],
    award: { max: 20000, costSharePct: 100, basis: 'Per-acre incentive payments, up to $20,000 per operation' },
    deadline: { kind: 'annual', month: 3, day: 1, label: 'Sign-up deadline' },
    practices: [{ code: '590', name: 'Voluntary nutrient management plan (per-acre incentive)', topics: ['nutrients', 'water-quality'], operations: ALL, unit: '100 acres', unitCost: 1000 }, P.cover],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Ohio'),
  },
  {
    id: 'ks-scc',
    name: 'Water Resources Cost-Share Program',
    shortName: 'Kansas cost-share',
    agency: 'Kansas Department of Agriculture, Division of Conservation',
    level: 'State',
    state: 'KS',
    summary: 'Cost share for practices that protect water quality, including livestock waste control.',
    topics: ['conservation', 'water-quality', 'manure'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['KS'] }, { kind: 'operation', operations: ALL }],
    award: { max: 15000, costSharePct: 70, basis: 'Up to 70% of practice cost' },
    deadline: { kind: 'annual', month: 10, day: 15, label: 'Conservation district sign-up deadline' },
    practices: [{ name: 'Livestock waste control system', topics: ['manure', 'water-quality'], operations: LIVESTOCK, unit: 'site', unitCost: 45000 }, P.waterway, P.grazing],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Kansas'),
  },
  {
    id: 'mo-swc',
    name: 'Soil and Water Conservation Cost-Share Program',
    shortName: 'Missouri cost-share',
    agency: 'Missouri Department of Natural Resources',
    level: 'State',
    state: 'MO',
    summary: 'Cost share funded by the state parks and soils sales tax for soil, nutrient and grazing practices.',
    topics: ['conservation', 'water-quality', 'nutrients', 'manure'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['MO'] }, { kind: 'operation', operations: ALL }],
    award: { max: 20000, costSharePct: 75, basis: 'Up to 75% of practice cost' },
    deadline: { kind: 'rolling', label: 'Rolling, through the county district' },
    practices: [P.nmp, P.grazing, P.waterway],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Missouri'),
  },
  {
    id: 'tx-wqmp',
    name: 'Water Quality Management Plan cost-share',
    shortName: 'Texas WQMP',
    agency: 'Texas State Soil and Water Conservation Board',
    level: 'State',
    state: 'TX',
    summary: 'A site-specific water quality plan plus cost share for the practices in it.',
    topics: ['water-quality', 'manure', 'nutrients'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['TX'] }, { kind: 'operation', operations: ALL }],
    award: { max: 15000, costSharePct: 75, basis: 'Up to 75% of practice cost' },
    deadline: { kind: 'rolling', label: 'Rolling, through the local district' },
    practices: [P.nmp, P.hua, P.grazing],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Texas'),
  },
  {
    id: 'pa-reap',
    name: 'Resource Enhancement and Protection tax credit',
    shortName: 'Pennsylvania REAP',
    agency: 'Pennsylvania State Conservation Commission',
    level: 'State',
    state: 'PA',
    summary: 'State tax credits for conservation and manure practices under an approved plan.',
    topics: ['manure', 'nutrients', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'state', states: ['PA'] },
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Current conservation plan and manure management plan' },
    ],
    award: { max: 250000, costSharePct: 75, basis: 'Tax credit of 50 to 75% of project cost, up to $250,000 per operation' },
    deadline: { kind: 'annual', month: 8, day: 1, label: 'Applications open each August, first come' },
    practices: [P.storage, P.nmp, P.cover],
    attachments: ['REAP application', 'Conservation plan and manure management plan', 'Invoices or quotes'],
    applyVia: 'The State Conservation Commission (REAP program office)',
  },
  {
    id: 'wi-swrm',
    name: 'Soil and Water Resource Management cost-share',
    shortName: 'Wisconsin SWRM',
    agency: 'Wisconsin Department of Agriculture, Trade and Consumer Protection',
    level: 'State',
    state: 'WI',
    summary: 'Cost share through county land conservation departments for manure storage and nutrient practices.',
    topics: ['manure', 'nutrients', 'water-quality', 'conservation'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['WI'] }, { kind: 'operation', operations: ALL }],
    award: { max: 20000, costSharePct: 70, basis: 'Up to 70% of practice cost' },
    deadline: { kind: 'annual', month: 1, day: 31, label: 'County land conservation department deadline' },
    practices: [P.storage, P.nmp, P.cover],
    attachments: STATE_FORMS,
    applyVia: 'The county land conservation department',
  },
  {
    id: 'ok-llcs',
    name: 'Locally Led Cost-Share Program',
    shortName: 'Oklahoma cost-share',
    agency: 'Oklahoma Conservation Commission',
    level: 'State',
    state: 'OK',
    summary: 'County district cost share for grazing, erosion and water quality practices.',
    topics: ['conservation', 'water-quality'],
    operations: ALL,
    eligibility: [{ kind: 'state', states: ['OK'] }, { kind: 'operation', operations: ALL }],
    award: { max: 10000, costSharePct: 75, basis: 'Up to 75% of practice cost' },
    deadline: { kind: 'annual', month: 12, day: 1, label: 'District sign-up deadline' },
    practices: [P.grazing, P.waterway],
    attachments: STATE_FORMS,
    applyVia: DISTRICT('Oklahoma'),
  },
  {
    id: 'ca-ammp',
    name: 'Alternative Manure Management Program',
    shortName: 'California AMMP',
    agency: 'California Department of Food and Agriculture',
    level: 'State',
    state: 'CA',
    summary: 'Grants for dairy and livestock operations that change how manure is handled to cut methane.',
    topics: ['manure'],
    operations: LIVESTOCK,
    eligibility: [{ kind: 'state', states: ['CA'] }, { kind: 'operation', operations: LIVESTOCK }],
    award: { max: 750000, costSharePct: 100, basis: 'Up to 100% of project cost, up to $750,000' },
    deadline: { kind: 'annual', month: 3, day: 15, label: 'Solicitation deadline' },
    practices: [{ name: 'Solid separation and dry manure handling', topics: ['manure'], operations: LIVESTOCK, unit: 'site', unitCost: 210000 }],
    attachments: ['Grant application', 'Project budget', 'Greenhouse gas reduction estimate'],
    applyVia: 'The California Department of Food and Agriculture grants portal',
  },
]

// What each program can fund from a ThiboLiSoft purchase (demo mapping, simplified).
const FUNDS: Record<string, Grant['funds']> = {
  'nrcs-eqip': { products: ['agronomyview', 'fieldtrack', 'tracelink', 'feedopt', 'pastureview'], sharePct: 75, note: 'Precision nutrient management, grazing and record-keeping technology under the nutrient management (590) and prescribed grazing (528) practices.' },
  'nrcs-csp': { products: ['agronomyview', 'fieldtrack', 'pastureview'], sharePct: 60, note: 'Precision agriculture enhancements (E590, E528) paid as annual stewardship payments.' },
  'aphis-adt': { products: ['tracelink'], sharePct: 50, note: 'Traceability records that go with official electronic ID tags.' },
  'rd-reap': { products: ['barnsense', 'binsense'], sharePct: 50, note: 'Ventilation, fan and aeration controls that cut energy use count as energy efficiency improvements.' },
  'il-cpp': { products: ['agronomyview', 'fieldtrack'], sharePct: 60, note: 'Nutrient and field records that document the conservation practices.' },
  'ia-wqi': { products: ['agronomyview', 'fieldtrack'], sharePct: 50, note: 'Nitrogen management and field records for Nutrient Reduction Strategy practices.' },
  'in-cwi': { products: ['agronomyview', 'fieldtrack', 'tracelink'], sharePct: 50, note: 'Nutrient and manure records for district cost-share practices.' },
  'mn-agri-lig': { products: ['barnsense', 'herdtrack', 'healthwatch'], sharePct: 10, note: 'Barn monitoring and herd technology as part of a livestock facility investment.' },
  'nc-acsp': { products: ['tracelink', 'barnsense'], sharePct: 75, note: 'Waste management records and lagoon-level monitoring for animal waste plans.' },
  'oh-h2ohio': { products: ['agronomyview', 'fieldtrack'], sharePct: 50, note: 'Voluntary nutrient management plan records and variable-rate recommendations.' },
  'mo-swc': { products: ['agronomyview', 'pastureview'], sharePct: 75, note: 'Nutrient and grazing management records.' },
  'tx-wqmp': { products: ['tracelink', 'pastureview'], sharePct: 75, note: 'Records that document the water quality management plan.' },
  'pa-reap': { products: ['agronomyview', 'fieldtrack', 'barnsense'], sharePct: 75, note: 'Precision agriculture and barn monitoring equipment under an approved plan.' },
  'wi-swrm': { products: ['agronomyview', 'fieldtrack'], sharePct: 70, note: 'Nutrient management plan records.' },
  'ok-llcs': { products: ['pastureview'], sharePct: 75, note: 'Grazing management records.' },
  'irs-rd': { products: ['herdtrack', 'feedopt', 'barnsense', 'healthwatch', 'tracelink', 'pastureview', 'fieldtrack', 'agronomyview', 'binsense', 'advisory'], sharePct: 8, note: 'The share of the subscription used in on-farm trials (rations, ventilation settings, variable-rate seeding) may count toward qualified research expenses. Staff time on the trials usually counts for more; the accountant decides.' },
}

const EXTRA: CatalogEntry[] = [
  {
    id: 'rd-reap',
    name: 'Rural Energy for America Program (energy efficiency grants)',
    shortName: 'USDA REAP',
    agency: 'USDA Rural Development',
    level: 'Federal',
    summary: 'Grants toward energy efficiency improvements on farms, such as ventilation, fan and grain aeration controls.',
    topics: ['conservation'],
    operations: ALL,
    eligibility: [
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'At least half of gross income from agricultural operations' },
      { kind: 'confirm', label: 'Energy assessment or audit for the project' },
      { kind: 'confirm', label: 'SAM.gov registration (UEI number)' },
    ],
    award: { max: 500000, costSharePct: 50, basis: 'Up to 50% of eligible project costs, up to $500,000 for energy efficiency' },
    deadline: { kind: 'quarterly', dates: [[10, 31], [1, 31], [3, 31], [6, 30]], label: 'Quarterly application windows' },
    practices: [],
    attachments: ['REAP grant application (Form RD 4280-3B)', 'Energy assessment', 'Quotes for the equipment and subscription', 'SAM.gov registration'],
    applyVia: 'The USDA Rural Development state office',
    sourceUrl: 'https://www.rd.usda.gov/',
  },
  {
    id: 'irs-rd',
    kind: 'Tax credit',
    name: 'Credit for Increasing Research Activities (IRC §41, Form 6765)',
    shortName: 'Federal R&D tax credit',
    agency: 'Internal Revenue Service (with the customer’s accountant)',
    level: 'Federal',
    summary: 'A federal tax credit for qualified research. Farms that run structured trials (rations, ventilation settings, seeding rates) with our data may have qualifying costs. Something to review with the customer’s accountant, not a grant application.',
    topics: [],
    operations: ALL,
    eligibility: [
      { kind: 'operation', operations: ALL },
      { kind: 'confirm', label: 'Activities meet the four-part test (technological, uncertainty, experimentation, permitted purpose)' },
      { kind: 'confirm', label: 'Trial records kept while the work happens' },
      { kind: 'confirm', label: 'Accountant confirms the credit and any state R&D credit' },
    ],
    award: { max: 250000, costSharePct: 8, basis: 'Roughly 6 to 10% of qualified research expenses under the simplified method; the accountant sets the real figure' },
    deadline: { kind: 'annual', month: 4, day: 15, label: 'Claimed with the federal return (Form 6765)' },
    practices: [],
    attachments: ['Trial plans and results from ThiboLiSoft records', 'Staff time on trials', 'Subscription invoices for the trial period'],
    applyVia: 'The customer’s accountant, on the federal return',
  },
]

const CATALOG: Grant[] = [...ENTRIES, ...EXTRA].map((g) => ({ ...g, kind: g.kind ?? 'Grant', funds: g.funds ?? FUNDS[g.id] ?? { products: [], sharePct: 0, note: '' } }))

const BY_ID: Record<string, Grant> = Object.fromEntries(CATALOG.map((g) => [g.id, g]))

export const seededGrants: GrantSource = {
  name: 'Seeded grant directory',
  disclaimer: 'Demo data. Program names are real; amounts, deadlines and eligibility are simplified and not current. Confirm with the agency before applying.',
  list: () => CATALOG,
  get: (id) => BY_ID[id],
  find: ({ state, topics, operations }: GrantQuery) =>
    CATALOG.filter((g) => (g.level === 'Federal' || g.state === state) && g.topics.some((t) => topics.includes(t)) && (!operations || g.operations.some((o) => operations.includes(o)))),
}
